apiVersion: batch/v1
kind: Job
metadata:
  name: pytorch-training-job
  namespace: ml-training
spec:
  backoffLimit: 2
  template:
    metadata:
      labels:
        app: pytorch-training
    spec:
      restartPolicy: Never
      containers:
        - name: trainer
          image: mlops-train:v1
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: config-volume
              mountPath: /app/configs
            - name: data-volume
              mountPath: /app/data
            - name: checkpoint-volume
              mountPath: /app/checkpoints
          resources:
            requests:
              cpu: "2"
              memory: "4Gi"
            limits:
              cpu: "2"
              memory: "4Gi"
              # Bonus GPU request (uncomment for GPU nodes)
              # nvidia.com/gpu: "1"
      volumes:
        - name: config-volume
          configMap:
            name: training-config
        - name: data-volume
          persistentVolumeClaim:
            claimName: ml-data-pvc
        - name: checkpoint-volume
          persistentVolumeClaim:
            claimName: ml-checkpoints-pvc